# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.thymeleaf.mode=HTML5

# Persist data between local runs.
spring.datasource.url=jdbc:h2:file:~/landon-hotel-booking-db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jackson.serialization.write_dates_as_timestamps=false
